name = "tigermove"
main = "./dist/server/index.js"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "MATCH", class_name = "Match" },
  { name = "MATCHMAKING", class_name = "MatchmakingQueue" },
]

[[migrations]]
tag = "v1"
new_classes = ["Match", "MatchmakingQueue"]
